syntax = "proto3";
package ttrpg_character_tools;

import "options.proto";
import "character_stats.proto";
import "character_skills.proto";
import "character_life.proto";
import "character_alignment.proto";
import "character_class_info.proto";
import "character_spells.proto";
import "character_build_choice.proto";
import "google/protobuf/timestamp.proto";

message Character {
  string id = 1;
  string name = 2;
  google.protobuf.Timestamp createdTimestamp = 5;
  Options options = 6;
  string background = 8;
  string race = 9;
  string subRace = 10;
  optional int32 xp = 11;
  CharacterAlignment alignment = 12;
  CharacterLife life = 13;
  CharacterStats stats = 14;
  CharacterSkills skills = 15;
  repeated CharacterClassInfo classInfo = 17;
  CharacterSpells spells = 18;
  optional int32 inspiration = 19;
  map<string, CharacterBuildChoice> characterBuildChoices = 21;
}
